# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/lehat/OneDrive/Desktop/CMPE140Lab7/Project_Lab8_Test/Project_Lab8_Test.runs/synth_1/Single_Cyc_SoC_fpga.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_msg_config  -id {17-179}  -suppress 
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/lehat/OneDrive/Desktop/CMPE140Lab7/Project_Lab8_Test/Project_Lab8_Test.cache/wt [current_project]
set_property parent.project_path C:/Users/lehat/OneDrive/Desktop/CMPE140Lab7/Project_Lab8_Test/Project_Lab8_Test.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_output_repo c:/Users/lehat/OneDrive/Desktop/CMPE140Lab7/Project_Lab8_Test/Project_Lab8_Test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_mem C:/Users/lehat/OneDrive/Desktop/CMPE140Lab7/Project_Lab8_Test/Project_Lab8_Test.srcs/sources_1/imports/Downloads/memfile1.dat
read_verilog -library xil_defaultlib {
  C:/Users/lehat/OneDrive/Desktop/CMPE140Lab7/Project_Lab8_Test/Project_Lab8_Test.srcs/sources_1/imports/cmpe140lab7v3.srcs/sources_1/new/CU.v
  C:/Users/lehat/OneDrive/Desktop/CMPE140Lab7/Project_Lab8_Test/Project_Lab8_Test.srcs/sources_1/imports/cmpe140lab7v3.srcs/sources_1/new/DP.v
  C:/Users/lehat/OneDrive/Desktop/CMPE140Lab7/Project_Lab8_Test/Project_Lab8_Test.srcs/sources_1/imports/cmpe140lab7v3.srcs/sources_1/new/Single_Cyc_SoC.v
  C:/Users/lehat/OneDrive/Desktop/CMPE140Lab7/Project_Lab8_Test/Project_Lab8_Test.srcs/sources_1/imports/cmpe140lab7v3.srcs/sources_1/new/SoC_ad.v
  C:/Users/lehat/OneDrive/Desktop/CMPE140Lab7/Project_Lab8_Test/Project_Lab8_Test.srcs/sources_1/imports/cmpe140lab7v3.srcs/sources_1/new/SoC_mux4.v
  C:/Users/lehat/OneDrive/Desktop/CMPE140Lab7/Project_Lab8_Test/Project_Lab8_Test.srcs/sources_1/imports/single_cycle_mips_source_initial/datapath/adder.v
  C:/Users/lehat/OneDrive/Desktop/CMPE140Lab7/Project_Lab8_Test/Project_Lab8_Test.srcs/sources_1/imports/single_cycle_mips_source_initial/datapath/alu.v
  C:/Users/lehat/OneDrive/Desktop/CMPE140Lab7/Project_Lab8_Test/Project_Lab8_Test.srcs/sources_1/imports/single_cycle_mips_source_initial/control_unit/auxdec.v
  C:/Users/lehat/OneDrive/Desktop/CMPE140Lab7/Project_Lab8_Test/Project_Lab8_Test.srcs/sources_1/imports/basys3_single_cycle_mips_validation/button_debouncer.v
  C:/Users/lehat/OneDrive/Desktop/CMPE140Lab7/Project_Lab8_Test/Project_Lab8_Test.srcs/sources_1/imports/basys3_single_cycle_mips_validation/clk_gen.v
  C:/Users/lehat/OneDrive/Desktop/CMPE140Lab7/Project_Lab8_Test/Project_Lab8_Test.srcs/sources_1/imports/cmpe140lab7v3.srcs/sources_1/new/cmp.v
  C:/Users/lehat/OneDrive/Desktop/CMPE140Lab7/Project_Lab8_Test/Project_Lab8_Test.srcs/sources_1/imports/cmpe140lab7v3.srcs/sources_1/new/cnt.v
  C:/Users/lehat/OneDrive/Desktop/CMPE140Lab7/Project_Lab8_Test/Project_Lab8_Test.srcs/sources_1/imports/single_cycle_mips_source_initial/control_unit/controlunit.v
  C:/Users/lehat/OneDrive/Desktop/CMPE140Lab7/Project_Lab8_Test/Project_Lab8_Test.srcs/sources_1/imports/single_cycle_mips_source_initial/datapath/datapath.v
  C:/Users/lehat/OneDrive/Desktop/CMPE140Lab7/Project_Lab8_Test/Project_Lab8_Test.srcs/sources_1/imports/single_cycle_mips_source_initial/memory/dmem.v
  C:/Users/lehat/OneDrive/Desktop/CMPE140Lab7/Project_Lab8_Test/Project_Lab8_Test.srcs/sources_1/imports/single_cycle_mips_source_initial/datapath/dreg.v
  C:/Users/lehat/OneDrive/Desktop/CMPE140Lab7/Project_Lab8_Test/Project_Lab8_Test.srcs/sources_1/imports/cmpe140lab7v3.srcs/sources_1/new/fact.v
  C:/Users/lehat/OneDrive/Desktop/CMPE140Lab7/Project_Lab8_Test/Project_Lab8_Test.srcs/sources_1/imports/cmpe140lab7v3.srcs/sources_1/new/fact_ad.v
  C:/Users/lehat/OneDrive/Desktop/CMPE140Lab7/Project_Lab8_Test/Project_Lab8_Test.srcs/sources_1/imports/cmpe140lab7v3.srcs/sources_1/new/fact_and.v
  C:/Users/lehat/OneDrive/Desktop/CMPE140Lab7/Project_Lab8_Test/Project_Lab8_Test.srcs/sources_1/imports/cmpe140lab7v3.srcs/sources_1/new/fact_done_reg.v
  C:/Users/lehat/OneDrive/Desktop/CMPE140Lab7/Project_Lab8_Test/Project_Lab8_Test.srcs/sources_1/imports/cmpe140lab7v3.srcs/sources_1/new/fact_err_reg.v
  C:/Users/lehat/OneDrive/Desktop/CMPE140Lab7/Project_Lab8_Test/Project_Lab8_Test.srcs/sources_1/imports/cmpe140lab7v3.srcs/sources_1/new/fact_mul.v
  C:/Users/lehat/OneDrive/Desktop/CMPE140Lab7/Project_Lab8_Test/Project_Lab8_Test.srcs/sources_1/imports/cmpe140lab7v3.srcs/sources_1/new/fact_mux.v
  C:/Users/lehat/OneDrive/Desktop/CMPE140Lab7/Project_Lab8_Test/Project_Lab8_Test.srcs/sources_1/imports/cmpe140lab7v3.srcs/sources_1/new/fact_mux4.v
  C:/Users/lehat/OneDrive/Desktop/CMPE140Lab7/Project_Lab8_Test/Project_Lab8_Test.srcs/sources_1/imports/cmpe140lab7v3.srcs/sources_1/new/fact_reg.v
  C:/Users/lehat/OneDrive/Desktop/CMPE140Lab7/Project_Lab8_Test/Project_Lab8_Test.srcs/sources_1/imports/cmpe140lab7v3.srcs/sources_1/new/fact_top.v
  C:/Users/lehat/OneDrive/Desktop/CMPE140Lab7/Project_Lab8_Test/Project_Lab8_Test.srcs/sources_1/imports/cmpe140lab7v3.srcs/sources_1/new/gpio_ad.v
  C:/Users/lehat/OneDrive/Desktop/CMPE140Lab7/Project_Lab8_Test/Project_Lab8_Test.srcs/sources_1/imports/cmpe140lab7v3.srcs/sources_1/new/gpio_mux4.v
  C:/Users/lehat/OneDrive/Desktop/CMPE140Lab7/Project_Lab8_Test/Project_Lab8_Test.srcs/sources_1/imports/cmpe140lab7v3.srcs/sources_1/new/gpio_reg.v
  C:/Users/lehat/OneDrive/Desktop/CMPE140Lab7/Project_Lab8_Test/Project_Lab8_Test.srcs/sources_1/imports/cmpe140lab7v3.srcs/sources_1/new/gpio_top.v
  C:/Users/lehat/OneDrive/Desktop/CMPE140Lab7/Project_Lab8_Test/Project_Lab8_Test.srcs/sources_1/imports/basys3_single_cycle_mips_validation/hex_to_7seg.v
  C:/Users/lehat/OneDrive/Desktop/CMPE140Lab7/Project_Lab8_Test/Project_Lab8_Test.srcs/sources_1/imports/single_cycle_mips_source_initial/memory/imem.v
  C:/Users/lehat/OneDrive/Desktop/CMPE140Lab7/Project_Lab8_Test/Project_Lab8_Test.srcs/sources_1/imports/basys3_single_cycle_mips_validation/led_mux.v
  C:/Users/lehat/OneDrive/Desktop/CMPE140Lab7/Project_Lab8_Test/Project_Lab8_Test.srcs/sources_1/imports/single_cycle_mips_source_initial/control_unit/maindec.v
  C:/Users/lehat/OneDrive/Desktop/CMPE140Lab7/Project_Lab8_Test/Project_Lab8_Test.srcs/sources_1/imports/single_cycle_mips_source_initial/mips/mips.v
  C:/Users/lehat/OneDrive/Desktop/CMPE140Lab7/Project_Lab8_Test/Project_Lab8_Test.srcs/sources_1/imports/single_cycle_mips_source_initial/datapath/mux2.v
  C:/Users/lehat/OneDrive/Desktop/CMPE140Lab7/Project_Lab8_Test/Project_Lab8_Test.srcs/sources_1/imports/cmpe140lab7v3.srcs/sources_1/new/regdff.v
  C:/Users/lehat/OneDrive/Desktop/CMPE140Lab7/Project_Lab8_Test/Project_Lab8_Test.srcs/sources_1/imports/single_cycle_mips_source_initial/datapath/regfile.v
  C:/Users/lehat/OneDrive/Desktop/CMPE140Lab7/Project_Lab8_Test/Project_Lab8_Test.srcs/sources_1/imports/single_cycle_mips_source_initial/datapath/signext.v
  C:/Users/lehat/OneDrive/Desktop/CMPE140Lab7/Project_Lab8_Test/Project_Lab8_Test.srcs/sources_1/imports/cmpe140lab7v3.srcs/sources_1/new/Single_Cyc_SoC_fpga.v
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/lehat/OneDrive/Desktop/CMPE140Lab7/Project_Lab8_Test/Project_Lab8_Test.srcs/constrs_1/imports/validation_wrapper/mips_fpga.xdc
set_property used_in_implementation false [get_files C:/Users/lehat/OneDrive/Desktop/CMPE140Lab7/Project_Lab8_Test/Project_Lab8_Test.srcs/constrs_1/imports/validation_wrapper/mips_fpga.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top Single_Cyc_SoC_fpga -part xc7a35tcpg236-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Single_Cyc_SoC_fpga.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file Single_Cyc_SoC_fpga_utilization_synth.rpt -pb Single_Cyc_SoC_fpga_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
